services:
  - type: web
    name: revive-auctions
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 600 --workers 1
    envVars:
      - key: SHEET_URL
        sync: false
